[build]
command = "npx prisma generate && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20.19.0"

[functions]
  directory = "Netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
